import os

Import('env')

_INCLUDES = [Dir('../src').abspath]

_SOURCES = ['Profiler.cpp']
_SOURCES = [File('../src/' + s).abspath for s in _SOURCES]

env.Append(APP_SOURCES = _SOURCES)
env.Append(CPPPATH = _INCLUDES)

if ('PROFILE' in env) and env['PROFILE']:
    env.Append(CCFLAGS = '-DCI_PROFILING')

Return('env')
